fix(textField): add responsivity to textfield
okp4/ui pull request #210
Opened 2022-05-18 15:55 UTC by lolottetheclash

This PR implements these following specifications : https://github.com/okp4/ui/issues/209

2022-05-18 16:11 UTC, fredericvilcot requested changes
That's a good catch for your first PR! 🚀
I just wrote a very minor remark, it's up to you!

2022-05-18 16:11 UTC, fredericvilcot commented on src/ui/atoms/textField/TextField.tsx
> +  const containerClass = classNames(`okp4-text-field-main ${size}`, { 'full-width': fullWidth })
You could use here shortcut syntax for object: 
```suggestion
  const containerClass = classNames(`okp4-text-field-main ${size}`, { fullWidth })
```

2022-05-18 16:13 UTC, fredericvilcot commented on src/ui/atoms/textField/TextField.tsx
> +  const containerClass = classNames(`okp4-text-field-main ${size}`, { 'full-width': fullWidth })
My bad 😜

2022-05-18 16:16 UTC, fredericvilcot submitted a review, later dismissed
Great!

2022-05-19 08:04 UTC, ErikssonJoakim submitted a review, later dismissed

2022-05-20 13:38 UTC, ccamel approved these changes

2022-05-23 11:18 UTC, fredericvilcot approved these changes

2022-05-23 11:39 UTC, merged