fix: increase padding size due to polygon
okp4/ui pull request #236
Opened 2022-05-24 14:02 UTC by lolottetheclash

2022-05-24 16:25 UTC, fredericvilcot approved these changes

2022-05-24 17:46 UTC, ccamel submitted a review, later dismissed

2022-05-25 07:15 UTC, ErikssonJoakim requested changes
For me the padding must be much bigger to get the `header` element out of the polygon. How about if we give the `header` div a padding-left instead? this way we keep the padding for the other elements

2022-05-30 08:19 UTC, ErikssonJoakim submitted a review, later dismissed
I see now how another PR will solve this issue 😃 👍  Good for me

2022-05-30 09:43 UTC, fredericvilcot approved these changes

2022-05-30 09:44 UTC, ErikssonJoakim approved these changes

2022-05-30 09:50 UTC, ccamel approved these changes

2022-05-30 09:52 UTC, merged