docs: add icon story to progress bar
okp4/ui pull request #405
Opened 2022-07-28 15:21 UTC by JoeyDjr

Add the story Icon of the `ProgressBar` component.

(It is better to merge the PR https://github.com/okp4/ui/pull/404 before that one.)

2022-07-28 15:36 UTC, fredericvilcot requested changes

2022-07-28 15:36 UTC, fredericvilcot commented on stories/atoms/components/progressBar/ProgressBar.stories.mdx
> +      return (
As it's not used, you don't need this lambda function anymore 😉

2022-07-28 15:36 UTC, fredericvilcot commented on stories/atoms/components/progressBar/ProgressBar.stories.mdx
> +            label="Lesson completed !"
```suggestion
            label="Lesson completed!"
```

2022-07-28 15:36 UTC, fredericvilcot commented on stories/atoms/components/progressBar/ProgressBar.stories.mdx
> +The `icon` property allows you to display an icon (or any `JSX.Element` at the right of the progress bar).<br />
```suggestion
The `icon` property allows you to display an icon (or any `JSX.Element`) at the right of the progress bar.<br />
```

2022-07-29 10:10 UTC, fredericvilcot commented on stories/atoms/components/progressBar/ProgressBar.stories.mdx
> +The `icon` property allows you to display an icon (or any `JSX.Element`) at the right of the progress bar.<br />
@JoeyDjr there is a surviving `<br />` tag here 😜

2022-07-29 12:43 UTC, fredericvilcot approved these changes

2022-07-29 14:00 UTC, ccamel approved these changes

2022-07-29 14:19 UTC, merged