Feat/add textarea to textfield
okp4/ui pull request #447
Opened 2022-08-19 15:02 UTC by JoeyDjr

This PR is about adding the multiline property to the `TextField` 

It is linked to the issue https://github.com/okp4/ui/issues/446

2022-08-22 13:00 UTC, fredericvilcot requested changes
Great job, I wrote down some remarks, it's up to you 😌

2022-08-22 13:12 UTC, JoeyDjr commented on src/ui/atoms/inputBase/InputBase.tsx
> +  readonly textareaRef?: RefObject<HTMLTextAreaElement>
We can't pass a ref of type `RefObject<HTMLInputElement  | HTMLTextAreaElement>` to a `textarea` 😔

2022-08-22 13:14 UTC, fredericvilcot commented on src/ui/atoms/inputBase/InputBase.tsx
> +  readonly textareaRef?: RefObject<HTMLTextAreaElement>
Yes but you can cast the type because you know on which component the ref is applied no?

2022-08-22 13:15 UTC, JoeyDjr commented on src/ui/atoms/inputBase/InputBase.tsx
> +  readonly textareaRef?: RefObject<HTMLTextAreaElement>
I will try and tell you

2022-08-22 13:17 UTC, JoeyDjr commented on src/ui/atoms/inputBase/InputBase.tsx
> +  readonly textareaRef?: RefObject<HTMLTextAreaElement>
@fredericvilcot I can write something like that : `ref={ref as RefObject<HTMLTextAreaElement>}`

2022-08-22 13:19 UTC, fredericvilcot commented on src/ui/atoms/inputBase/InputBase.tsx
> +  readonly textareaRef?: RefObject<HTMLTextAreaElement>
Yep, LGTM

2022-08-22 14:07 UTC, fredericvilcot approved these changes
LGTM! 😎

2022-08-22 14:35 UTC, lolottetheclash approved these changes
Well done!

2022-08-23 07:37 UTC, ccamel approved these changes

2022-08-23 09:46 UTC, merged