Feat/listitem as children of list
okp4/ui pull request #454
Opened 2022-08-22 09:51 UTC by JoeyDjr

This PR is about the issue https://github.com/okp4/ui/issues/453

2022-08-22 10:13 UTC, lolottetheclash requested changes
Nice! Just a few remarks ;)

2022-08-22 10:13 UTC, lolottetheclash commented on src/ui/atoms/list/List.tsx
> +  return <div className="okp4-list-main">{children}</div>
I think you can remove the useless `return` here

2022-08-22 10:13 UTC, lolottetheclash commented on stories/atoms/components/list/List.stories.mdx
You should also remove `argTypes` since we no longer use `items`.

2022-08-22 10:13 UTC, lolottetheclash commented on stories/atoms/components/listItem/ListItem.stories.mdx
> +      <List>
And you also can remove this part of code: 
` items: {
      table: {
        disable: true
      }
    }` from the `argTypes`

2022-08-22 19:23 UTC, fredericvilcot approved these changes
LGTM!

2022-08-23 06:02 UTC, lolottetheclash approved these changes
👍

2022-08-23 09:14 UTC, ErikssonJoakim approved these changes

2022-08-23 09:43 UTC, merged