Feat/colors palette
okp4/ui pull request #46
Opened 2022-03-07 11:25 UTC by fredericvilcot

This PR implements the colors palette defined at OKP4.

There is a lot of naming conventions for colors, so I suggested to define names according to [Geoff Graham](https://geoffgraham.me/) guidelines, which seems to be smart for our design system. (👉 variables grouped by color)

OKP4 palette : 
![Capture d’écran 2022-03-07 à 12 24 40](https://user-images.githubusercontent.com/47554752/157022376-44f0a65d-4b8e-4d99-af2e-518a9c9e7412.png)

2022-03-07 13:28 UTC, ccamel commented
It seems that the rule `color-named`, specified in [stylelintrc.json](https://github.com/okp4/ui/blob/main/.stylelintrc.json#L7) is not really suitable for our needs.

2022-03-07 13:32 UTC, ccamel requested changes
Nice work. :+1: 

I'd suggest to move all the things related to the stories into the folder `stories`. The folder `src` should only contain the source code of the library.

2022-03-07 13:43 UTC, amimart approved these changes

2022-03-07 16:31 UTC, nperon approved these changes

2022-03-08 09:44 UTC, fredericvilcot commented
@ccamel I suggest not to implement more colors and gradients in the palette because Vincent continues to experiment with new colors to determine the visual identity of okp4...

2022-03-08 09:57 UTC, ccamel commented
Ok. Fine for me.

2022-03-08 10:53 UTC, ad2ien submitted a review, later dismissed

2022-03-08 13:40 UTC, ccamel approved these changes

2022-03-08 14:43 UTC, amimart requested changes

2022-03-08 14:43 UTC, amimart commented on stories/brand/colors/Color.stories.tsx
> +     * References the key of expoted the variable in the color palette.
```suggestion
     * References the key of the exported variable in the color palette.
```

Little typo ? 👨‍🏫

2022-03-08 17:14 UTC, fredericvilcot commented on stories/brand/colors/Color.stories.tsx
> +     * References the key of expoted the variable in the color palette.
Ahahah yep, I'll make the change 😜

2022-03-09 09:32 UTC, fredericvilcot commented
Everything has been cleaned, if it's ok for you, let's merge it 🚀

2022-03-09 10:08 UTC, amimart approved these changes

2022-03-09 10:22 UTC, ccamel approved these changes

2022-03-09 10:28 UTC, merged