Feat/add wallet
okp4/ui pull request #68
Opened 2022-03-16 14:15 UTC by fredericvilcot

This PR carries the first stage of construction of the `Wallet` organism by building in particular the architectural design.

***Architecture***

Wallet is built upon [hexagonal architecture](https://blog.octo.com/architecture-hexagonale-trois-principes-et-un-exemple-dimplementation/) that allows to decouple all business logic from UI framework and ensures maximum testability and scalability.
In this feature, this kind of architecture allows to switch from any kind of wallet and to systematically provide the user with the same associated service.

***Purpose***

This first implementation allows user to enable [Keplr wallet](https://wallet.keplr.app/#/dashboard) and to retrieve all associated accounts that are represented by address / pubKey pairs per `chainId`

2022-03-16 14:48 UTC, ad2ien approved these changes
Very cool!

2022-03-16 15:38 UTC, amimart submitted a review, later dismissed

2022-03-16 16:02 UTC, ccamel requested changes
Good job! 👍 

A few small remarks, but nothing major, which I would be happy to discuss with you. Thanks.

2022-03-17 09:15 UTC, ccamel commented on src/gateways/KeplrWalletGateway.ts
> +    return window.Keplr.enable(chainId)
Tested in the console, the `enable()` can throw exceptions (I don't think it's clearly described in the official documentatin). So better wrap with a try/catch construct.

```
> window.keplr.enable("foo")
Promise {<pending>}
injectedScript.bundle.js:10 Uncaught (in promise) Error: There is no chain info for foo
    at r (injectedScript.bundle.js:10:32583)
```

2022-03-17 09:28 UTC, fredericvilcot commented on src/gateways/DTO/keplrDTO.ts
> +export type KeplrAccountDTO = AccountData
It was to enhance the mapping operation but I agree, it's unnecessary here ...

2022-03-17 09:29 UTC, fredericvilcot commented on src/domain/wallet/builders/account.builder.ts
> +    this.account.address = address
Thanks for highlighting this elements, it makes me understand better the final purpose of `builder` pattern !

2022-03-17 12:35 UTC, ccamel commented on src/gateways/DTO/keplrDTO.ts
> +export type KeplrAccountDTO = AccountData
Thanks 😌

2022-03-18 08:28 UTC, ccamel commented on src/domain/wallet/builders/account.builder.spec.ts
> +  describe('Given that publicKey is empty', () => {
As discussed together @fredericvilcot not relevant to me. Let's find a way to disable that rule.

2022-03-18 08:28 UTC, ccamel commented on src/domain/wallet/builders/account.builder.spec.ts
> +  describe('Given that address is empty', () => {
As discussed together @fredericvilcot not relevant to me. Let's find a way to disable that rule.

2022-03-18 10:43 UTC, ccamel approved these changes
Amazing work! 😻

2022-03-18 10:45 UTC, amimart approved these changes

2022-03-18 10:46 UTC, merged