feat: text atomic element
okp4/ui pull request #88
Opened 2022-03-28 07:23 UTC by ad2ien

https://github.com/okp4/product/issues/466

2022-04-05 11:49 UTC, nperon submitted a review, later dismissed
Great!

2022-04-05 11:58 UTC, ErikssonJoakim approved these changes
Nice work!

2022-04-06 07:20 UTC, nperon submitted a review, later dismissed

2022-04-06 09:48 UTC, amimart requested changes
Some comments based on @ccamel ones in another PR 😉

2022-04-06 09:48 UTC, amimart commented on src/ui/styles/font.scss
> +  font-family: secondary-bold;
`secondary-block` & `secondary-black` are already defined above.

2022-04-06 09:48 UTC, amimart commented on src/ui/atoms/text/Text.tsx
> +export type TTextProps = DeepReadonly<{
Based on the @ccamel [comment](https://github.com/okp4/ui/pull/81#discussion_r843176700) the convention dictate to not prefix types with `T`.

2022-04-06 09:48 UTC, amimart commented on src/ui/atoms/text/Text.tsx
> +   * Prop used to switch out what's being ultimately rendered. By default, a `span` component.
Based on the @ccamel [comment](https://github.com/okp4/ui/pull/81#discussion_r843181124), maybe we need to remove the defaults notions here.

2022-04-07 08:57 UTC, amimart approved these changes

2022-04-07 09:21 UTC, fredericvilcot approved these changes
That's a great job, thanks! ☺️

2022-04-07 09:22 UTC, ccamel approved these changes
Really nice! 🥰

2022-04-07 09:22 UTC, merged