Feat/theme provider
okp4/ui pull request #91
Opened 2022-03-30 20:03 UTC by fredericvilcot

2022-04-02 15:54 UTC, fredericvilcot commented on src/ui/atoms/theme/ThemeSwitcher.tsx
> +export const ThemeSwitcher: React.FC = () => {
> Function `ThemeSwitcher` has 36 lines of code (exceeds 25 allowed). Consider refactoring.

@ccamel What can we do about codeclimate review which imposes a size limit even on React components ?

2022-04-04 08:19 UTC, nperon submitted a review, later dismissed

2022-04-04 10:16 UTC, ad2ien approved these changes
:+1: tested by importing it in an other react project!

2022-04-04 12:03 UTC, ccamel requested changes
Hey! What a good job. 👍 

I have some remarks and suggestions that we can look at together to finalize the PR. Thank you.

2022-04-04 12:03 UTC, ccamel commented on src/ui/atoms/theme/ThemeSwitcher.tsx
> +      localStorage.setItem('okp4UserTheme', newTheme)
@fredericvilcot I propose you to introduce a bunch of hooks to improve composability. Let's see this together.

2022-04-04 13:24 UTC, fredericvilcot commented on src/ui/atoms/canvas/Canvas.tsx
> +import { useAnimationFrame } from 'hooks/useAnimationFrame'
@ccamel, I changed it, I didn't notice it ...

2022-04-04 13:25 UTC, fredericvilcot commented on src/hooks/useTheme.ts
> +import type { ThemeContextType } from '../ui/atoms/theme/themeContext'
@ccamel You're right, I created a folder dedicated to context, as `hooks` depend now on context and not ui ...

2022-04-04 13:27 UTC, fredericvilcot commented on stories/atoms/brand/theme/Theme.stories.mdx
> +As an example, you could insert it in your header component to display it near toolbar actions :
👀

2022-04-04 16:14 UTC, fredericvilcot commented
@FYI @ErikssonJoakim

2022-04-04 16:14 UTC, amimart approved these changes

2022-04-04 16:16 UTC, ad2ien approved these changes
:clap: :clap: :clap:

2022-04-04 16:16 UTC, merged